# Generated by Django 4.2.5 on 2023-09-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollchoice',
            options={'ordering': ['order'], 'verbose_name': 'Poll choice', 'verbose_name_plural': 'Poll choices'},
        ),
        migrations.AddField(
            model_name='pollchoice',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
