# Generated by Django 4.2.5 on 2023-09-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number'),
        ('course', '0002_lessonmedia_delete_media'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonmedia',
            options={'verbose_name': 'Lesson Media', 'verbose_name_plural': 'Lesson Media'},
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('profile', 'lesson')},
        ),
    ]
