# Generated by Django 4.2.5 on 2023-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number'),
        ('course', '0003_alter_lessonmedia_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonMedia',
            new_name='LessonContent',
        ),
        migrations.RenameModel(
            old_name='LessonProgress',
            new_name='LessonView',
        ),
        migrations.AlterModelOptions(
            name='lessoncontent',
            options={'verbose_name': 'Lesson Content', 'verbose_name_plural': 'Lesson Contents'},
        ),
        migrations.AlterModelOptions(
            name='lessonview',
            options={'verbose_name': 'Lesson View', 'verbose_name_plural': 'Lesson Views'},
        ),
        migrations.AlterField(
            model_name='course',
            name='main_image',
            field=models.ImageField(upload_to='', verbose_name='Main Image'),
        ),
    ]
