# Generated by Django 4.2.5 on 2023-09-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_lessonmedia_lessoncontent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='points',
        ),
    ]
