# Generated by Django 4.2.5 on 2023-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_usercourse_unique_together_usercourse_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_optional',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration_time',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_day',
            field=models.IntegerField(default=None, verbose_name='Duration Day'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='expired_date',
            field=models.DateField(default=None, verbose_name='Expired Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='is_optional',
            field=models.BooleanField(default=False, verbose_name='Is Optional'),
        ),
    ]
