# Generated by Django 4.2.5 on 2023-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_category_is_optional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='score',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_optional',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='start_time',
        ),
        migrations.AddField(
            model_name='course',
            name='is_complate',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_course_end',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='end_day',
            field=models.DateField(blank=True, null=True, verbose_name='End Day'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='start_day',
            field=models.DateField(blank=True, null=True, verbose_name='Start Day'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='Is Finish'),
        ),
    ]
