# Generated by Django 4.2.5 on 2023-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_score_course_points_remove_course_is_optional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='points',
            field=models.IntegerField(verbose_name='Points'),
        ),
    ]
