# Generated by Django 4.2.5 on 2023-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_course_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_complate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_course_end',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='course',
            name='points',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='start_day',
        ),
        migrations.AddField(
            model_name='course',
            name='is_optional',
            field=models.BooleanField(default=False, verbose_name='Is Optional'),
        ),
        migrations.AddField(
            model_name='course',
            name='score',
            field=models.IntegerField(default=None, verbose_name='Score'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='end_time',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='start_time',
            field=models.DateField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
