# Generated by Django 4.2.5 on 2023-09-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_course_is_complate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'verbose_name': 'Course Review', 'verbose_name_plural': 'Course Reviews'},
        ),
    ]
