# Generated by Django 4.2.5 on 2023-09-14 11:06

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='certificate',
            field=models.FileField(default=django.utils.timezone.now, upload_to='document/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'csv', 'doc', 'doc'])], verbose_name='Certificate'),
            preserve_default=False,
        ),
    ]
