# Generated by Django 4.2.5 on 2023-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_document_file_document_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='JShShIR',
            field=models.CharField(default='test_name', max_length=255, verbose_name='JShShIR'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('bsc', 'Bachelor'), ('msc', 'Master'), ('stu', 'Student')], default='stu', max_length=55, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='test_name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('us', 'United States'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=255, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_series',
            field=models.CharField(default='test_name', max_length=255, verbose_name='Passport Series'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(default='test_name', max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_center',
            field=models.CharField(default='test_name', max_length=255, verbose_name='Study Center'),
        ),
    ]
