# Generated by Django 4.2.5 on 2023-09-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_jshshir_alter_profile_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='JShShIR',
            field=models.CharField(max_length=255, verbose_name='JShShIR'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(choices=[('bsc', 'Bachelor'), ('msc', 'Master'), ('stu', 'Student')], max_length=55, verbose_name='Degree'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(choices=[('us', 'United States'), ('uz', 'Uzbek'), ('ru', 'Russian')], max_length=255, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='passport_series',
            field=models.CharField(max_length=255, verbose_name='Passport Series'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(max_length=255, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=None, verbose_name='Score'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_center',
            field=models.CharField(max_length=255, verbose_name='Study Center'),
        ),
    ]
