# Generated by Django 4.2.5 on 2023-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_jshshir_alter_profile_degree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=None, verbose_name='Points'),
            preserve_default=False,
        ),
    ]
