# Generated by Django 4.2.5 on 2023-09-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_score_profile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=None, verbose_name='Score'),
            preserve_default=False,
        ),
    ]
