# Generated by Django 4.2.5 on 2023-09-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_points_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
