# Generated by Django 4.2.5 on 2023-09-14 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_document_file_document_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=200, verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='users.profile', verbose_name='Owner')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='webinar.comment', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('about', models.TextField(max_length=400, verbose_name='About')),
                ('stream_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Stream url')),
                ('status', models.CharField(choices=[('l', 'Live'), ('c', 'Completed'), ('p', 'Planned')], max_length=1, verbose_name='Status')),
                ('webinar_type', models.CharField(choices=[('l', 'Lecture'), ('s', 'Seminar')], max_length=1, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Webinar',
                'verbose_name_plural': 'Webinars',
            },
        ),
        migrations.CreateModel(
            name='WebinarSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(max_length=100, verbose_name='Search keyword')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_search_history', to='users.profile', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Webinar Search History',
                'verbose_name_plural': 'Webinar Search Histories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('complaint_type', models.CharField(choices=[('i', 'Illegal'), ('p', 'Personal'), ('a', 'Ad'), ('f', 'Fake'), ('o', 'Other')], max_length=1, verbose_name='Type')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='webinar.comment', verbose_name='Comment')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_complaints', to='users.profile', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Comment complaint',
                'verbose_name_plural': 'Comment complaints',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webinar.webinar', verbose_name='Webinar'),
        ),
    ]
